# Generated by Django 4.0.2 on 2022-03-01 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special_option_idx', models.IntegerField()),
                ('started_year', models.IntegerField(blank=True, null=True)),
                ('ended_year', models.IntegerField(blank=True, null=True)),
                ('basic_subject', models.IntegerField(blank=True, null=True)),
                ('necess_subject', models.IntegerField(blank=True, null=True)),
                ('major_total_subject', models.IntegerField(blank=True, null=True)),
                ('common_subject', models.IntegerField(blank=True, null=True)),
                ('key_subject', models.IntegerField(blank=True, null=True)),
                ('total_subjects', models.IntegerField(blank=True, null=True)),
                ('department_idx', models.IntegerField()),
                ('major_idx', models.IntegerField()),
                ('track_idx', models.IntegerField()),
                ('entry_route_idx', models.IntegerField()),
            ],
            options={
                'db_table': 'credit_requirements',
                'managed': False,
            },
        ),
    ]
