# Generated by Django 4.0.2 on 2022-02-28 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special_option_idx', models.IntegerField()),
                ('hased_options', models.CharField(blank=True, max_length=40, null=True)),
                ('entry_year', models.IntegerField(blank=True, null=True)),
                ('basic_subject', models.IntegerField(blank=True, null=True)),
                ('necess_subject', models.IntegerField(blank=True, null=True)),
                ('major_total_subject', models.IntegerField(blank=True, null=True)),
                ('common_subject', models.IntegerField(blank=True, null=True)),
                ('key_subject', models.IntegerField(blank=True, null=True)),
                ('total_subjects', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'micro_cases',
                'managed': False,
            },
        ),
    ]
