# Generated by Django 4.0.2 on 2022-03-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PinnocchioConsultingProject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectType1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_type_1_idx', models.IntegerField()),
                ('subject_type_1_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'subject_type_1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubjectType2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_type_2_idx', models.IntegerField()),
                ('subject_type_2_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'subject_type_2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubjectType3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_type_3_idx', models.IntegerField()),
                ('subject_type_3_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'subject_type_3',
                'managed': False,
            },
        ),
    ]
